FROM rocker/tidyverse:4

# It does not fail if install failed
RUN Rscript -e "install.packages(c('markdown', 'gridExtra', 'RPostgres', 'arrow'))"

# refer to https://stackoverflow.com/questions/45289764/install-r-packages-using-docker-file
# RUN R -e "install.packages('markdown', version='1.1', dependencies=TRUE, type='binary', repos='http://cran.rstudio.com/')" && \
# R -e "install.packages('gridExtra', version='2.3', dependencies=TRUE, type='binary', repos='http://cran.rstudio.com/')" && \
# R -e "install.packages('RPostgres', version='1.4.3', dependencies=TRUE, type='binary', repos='http://cran.rstudio.com/')"